#!/usr/bin/env ruby

lib_dir = File.expand_path(File.dirname(__FILE__) + "/../lib")

$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'avalanche/cli'

cmd = Avalanche::CLI::Command.new('hello [options] NAME', {
  :title => ['--title TITLE', String, 'Desired title']
}, Proc.new do |opts, args|
  raise "NAME is required" if args.empty?

  puts "Hello, #{opts[:title]} #{args.first}!".gsub(/\s+/, " ")
end)

cmd.run(ARGV)
